### ISSUE TITLE
User guide transformations section contains mixed GB and US spelling

### ISSUE THREAD

**Issue by hepabolu** [podfeet/docsify-user-docs-xkpasswd#1]
The list of transformations contain the word 'capitalise' spelled as en GB, while the sentence below

`Note that the last option will not always generate a password with both upper and lower case letters, as it's random whether each word will be capitalized or not.`

spell its as en US. 
This looks a bit confusing

**Comment by podfeet** [comment]
Changed to British English for consistency.
