### ISSUE TITLE
Image caption wraps incorrectly

### ISSUE THREAD

**Issue by hepabolu** [podfeet/docsify-user-docs-xkpasswd#2]
![CleanShot 2024-09-10-23-33@2x](https://github.com/user-attachments/assets/03fefe62-54ac-4045-a9ed-a4bbecbde670)

Browser: Arc (based on Chrome)
when the width is very wide, the caption of the image does not stay below the image.

Suggestion: check if it's possible to tell Docsify that it's an image + caption combo.

**Comment by podfeet** [comment]
Please specify which document you're referring to for all issues in the user guide.

**Comment by podfeet** [comment]
I dug around for a while and found it but please include the doc name in the future.

Also this had nothing to do with Arc or Chrome. 

Fixed in 50efa1c4e74f734d66fd19a6a2cee1171accc587
